import { useState, useCallback, useEffect, useRef } from "react";
import {
  type Day,
  type TimetableSlot,
  type TimetableAction,
  type Teacher,
  type SlotType,
  type ValidationResult,
  type AutoGenerateResult,
  type SubjectQuota,
  type UserSettings,
  type Subject,
  DAYS,
} from "@shared/schema";
import {
  initializeTimetable,
  getSlotKey,
  validatePlacement,
} from "@/lib/timetable-utils";
import { TimetableGrid } from "@/components/timetable/timetable-grid";
import { TeacherSidebar } from "@/components/timetable/teacher-sidebar";
import { PlacementDialog } from "@/components/timetable/placement-dialog";
import { SubjectTracker } from "@/components/timetable/subject-tracker";
import { ActionHistory } from "@/components/timetable/action-history";
import { StatsHeader } from "@/components/timetable/stats-header";
import { AutoGenerateDialog } from "@/components/timetable/auto-generate-dialog";
import { useToast } from "@/hooks/use-toast";
import { useQuery, useMutation } from "@tanstack/react-query";
import { queryClient, apiRequest } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Save, Loader2, Trash2 } from "lucide-react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";

function extractApiErrorMessage(e: unknown, fallback: string): string {
  if (!(e instanceof Error)) return fallback;
  const match = e.message.match(/^(\d{3}):\s*([\s\S]*)$/);
  if (!match) return e.message || fallback;
  const status = Number(match[1]);
  const body = match[2].trim();
  if (status >= 500) return "Server error — please try again.";
  try {
    const parsed = JSON.parse(body) as {
      error?: string;
      validation?: { errors?: Array<{ message?: string }> };
      perClass?: Array<{ schoolClass?: string; validation?: { errors?: Array<{ message?: string }> } }>;
    };
    const failures = parsed.perClass?.filter(
      (r) => r.validation && r.validation.errors && r.validation.errors.length > 0,
    ) ?? [];
    if (failures.length > 1) {
      const first = failures[0].validation?.errors?.[0]?.message;
      return first
        ? `${failures.length} classes blocked it. First: ${first}`
        : `${failures.length} classes blocked this placement.`;
    }
    const firstError = parsed.validation?.errors?.[0]?.message;
    if (firstError) return firstError;
    if (parsed.error) return parsed.error;
  } catch {
    // body wasn't JSON — fall through
  }
  return body || fallback;
}

export default function Home() {
  const { toast } = useToast();

  const [timetable, setTimetable] = useState<Map<string, TimetableSlot>>(() =>
    initializeTimetable()
  );
  const [selectedDay, setSelectedDay] = useState<Day>("Monday");
  const [selectedSlot, setSelectedSlot] = useState<TimetableSlot | null>(null);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [autoGenDialogOpen, setAutoGenDialogOpen] = useState(false);
  const [validation, setValidation] = useState<ValidationResult | null>(null);

  const [actions, setActions] = useState<TimetableAction[]>([]);
  const [actionIndex, setActionIndex] = useState(-1);
  const gridRef = useRef<HTMLDivElement>(null);

  const [saveDialogOpen, setSaveDialogOpen] = useState(false);
  const [saveName, setSaveName] = useState("");
  const [resetDialogOpen, setResetDialogOpen] = useState(false);

  const { data: teachers = [] } = useQuery<Teacher[]>({
    queryKey: ["/api/teachers"],
  });

  const { data: timetableData } = useQuery<TimetableSlot[]>({
    queryKey: ["/api/timetable"],
  });

  const { data: quotas = [] } = useQuery<SubjectQuota[]>({
    queryKey: ["/api/quotas"],
  });

  const { data: userSettings } = useQuery<UserSettings>({
    queryKey: ["/api/settings"],
  });

  const { data: customSubjects = [] } = useQuery<Subject[]>({
    queryKey: ["/api/subjects"],
  });

  const fatigueLimit = userSettings?.fatigueLimit ?? 5;

  useEffect(() => {
    if (timetableData) {
      const newTimetable = new Map<string, TimetableSlot>();
      for (const slot of timetableData) {
        const key = getSlotKey(slot.day, slot.schoolClass, slot.period);
        newTimetable.set(key, slot);
      }
      setTimetable(newTimetable);
    }
  }, [timetableData]);

  const autoGenerateMutation = useMutation({
    mutationFn: async (options: { lockExisting: boolean; clearFirst: boolean }) => {
      const response = await apiRequest("POST", "/api/timetable/autogenerate", options);
      return response.json() as Promise<AutoGenerateResult>;
    },
    onSuccess: (result) => {
      queryClient.invalidateQueries({ queryKey: ["/api/timetable"] });
      if (result.success) {
        toast({
          title: "Timetable Generated",
          description: `Successfully placed ${result.slotsPlaced} periods. ${result.warnings.length > 0 ? `${result.warnings.length} warnings.` : ""}`,
        });
      } else {
        toast({
          title: "Generation Completed with Issues",
          description: result.errors.join(", "),
          variant: "destructive",
        });
      }
      // Keep the dialog open on success so the user sees the result summary
      // and can use the Save Timetable CTA in the footer.
      if (!result.success) {
        setAutoGenDialogOpen(false);
      }
    },
    onError: (error) => {
      toast({
        title: "Generation Failed",
        description: error instanceof Error ? error.message : "Unknown error",
        variant: "destructive",
      });
    },
  });

  const handleCellClick = useCallback((slot: TimetableSlot) => {
    setSelectedSlot(slot);
    setValidation(null);
    setDialogOpen(true);
  }, []);

  const handleValidate = useCallback(
    (
      subject: string,
      teacherId: string,
      slotType: SlotType,
      slashPairSubject?: string,
      slashPairTeacherId?: string
    ) => {
      if (!selectedSlot) return;

      const result = validatePlacement(timetable, teachers, {
        day: selectedSlot.day,
        period: selectedSlot.period,
        schoolClass: selectedSlot.schoolClass,
        subject,
        teacherId,
        slotType,
        slashPairSubject,
        slashPairTeacherId,
      }, fatigueLimit, customSubjects);

      setValidation(result);
    },
    [selectedSlot, timetable, teachers, fatigueLimit, customSubjects]
  );

  const handlePlace = useCallback(
    async (
      subject: string,
      teacherId: string,
      slotType: SlotType,
      slashPairSubject: string | undefined,
      slashPairTeacherId: string | undefined,
      options: { isActivity: boolean; isLocked: boolean; applyToAllClasses: boolean },
    ) => {
      if (!selectedSlot) return;

      // Activities and locked placements live in the database — they must
      // survive refresh and Clear & Generate. Persist them via the API,
      // then let /api/timetable refetch reseed local state.
      if (options.isActivity || options.isLocked) {
        try {
          const body: Record<string, unknown> = {
            day: selectedSlot.day,
            period: selectedSlot.period,
            schoolClass: selectedSlot.schoolClass,
            subject,
            slotType,
            isActivity: options.isActivity,
            isLocked: options.isLocked,
            applyToAllClasses: options.applyToAllClasses,
          };
          if (!options.isActivity) {
            if (teacherId) body.teacherId = teacherId;
            if (slotType === "slash") {
              if (slashPairSubject) body.slashPairSubject = slashPairSubject;
              if (slashPairTeacherId) body.slashPairTeacherId = slashPairTeacherId;
            }
          }
          const res = await apiRequest("POST", "/api/timetable/place", body);
          await res.json();
          await queryClient.invalidateQueries({ queryKey: ["/api/timetable"] });
          toast({
            title: options.isActivity ? "Activity scheduled" : "Period locked",
            description: options.applyToAllClasses
              ? `${subject} added to every class on ${selectedSlot.day} P${selectedSlot.period}`
              : `${subject} on ${selectedSlot.day} P${selectedSlot.period} (${selectedSlot.schoolClass})`,
          });
          setDialogOpen(false);
          setSelectedSlot(null);
          setValidation(null);
        } catch (e) {
          toast({
            title: "Could not save",
            description: extractApiErrorMessage(e, "Server rejected the placement."),
            variant: "destructive",
          });
        }
        return;
      }

      const validationResult = validatePlacement(timetable, teachers, {
        day: selectedSlot.day,
        period: selectedSlot.period,
        schoolClass: selectedSlot.schoolClass,
        subject,
        teacherId,
        slotType,
        slashPairSubject,
        slashPairTeacherId,
      }, fatigueLimit, customSubjects);

      if (!validationResult.isValid) {
        toast({
          title: "Cannot place subject",
          description: validationResult.errors[0]?.message || "Validation failed",
          variant: "destructive",
        });
        return;
      }

      setTimetable((prev) => {
        const newTimetable = new Map(prev);
        const key = getSlotKey(
          selectedSlot.day,
          selectedSlot.schoolClass,
          selectedSlot.period
        );

        const previousSlot = newTimetable.get(key);

        const newSlot: TimetableSlot = {
          ...selectedSlot,
          status: "occupied",
          subject,
          teacherId,
          slotType,
          slashPairSubject: slashPairSubject || null,
          slashPairTeacherId: slashPairTeacherId || null,
          isLocked: false,
        };

        newTimetable.set(key, newSlot);

        if (slotType === "double") {
          const nextKey = getSlotKey(
            selectedSlot.day,
            selectedSlot.schoolClass,
            selectedSlot.period + 1
          );
          const nextSlot = newTimetable.get(nextKey);
          if (nextSlot) {
            newTimetable.set(nextKey, {
              ...nextSlot,
              status: "occupied",
              subject,
              teacherId,
              slotType: "double",
              slashPairSubject: slashPairSubject || null,
              slashPairTeacherId: slashPairTeacherId || null,
              isLocked: false,
            });
          }
        }

        const action: TimetableAction = {
          id: crypto.randomUUID(),
          type: "place",
          timestamp: Date.now(),
          slot: newSlot,
          previousSlot: previousSlot || null,
        };

        setActions((prev) => {
          const newActions = prev.slice(0, actionIndex + 1);
          return [...newActions, action];
        });
        setActionIndex((prev) => prev + 1);

        return newTimetable;
      });

      const teacher = teachers.find((t) => t.id === teacherId);
      toast({
        title: "Subject scheduled",
        description: `${subject} with ${teacher?.name} on ${selectedSlot.day} P${selectedSlot.period}`,
      });

      setDialogOpen(false);
      setSelectedSlot(null);
      setValidation(null);
    },
    [selectedSlot, timetable, teachers, toast, actionIndex, fatigueLimit]
  );

  const handleRemove = useCallback(async () => {
    if (!selectedSlot) return;

    // Always hit the server. Auto-generated regular periods are persisted
    // to the database too (not just locked rows + activities), so a
    // local-only delete would leave a stranded DB row that blocks any
    // subsequent placement in the same cell with SLOT_OCCUPIED. A 404
    // means the cell wasn't persisted (purely local placement) — safe to
    // ignore. `force=true` is required for locked rows.
    try {
      const url =
        `/api/timetable/${encodeURIComponent(selectedSlot.day)}` +
        `/${encodeURIComponent(selectedSlot.schoolClass)}` +
        `/${selectedSlot.period}?force=true`;
      try {
        await apiRequest("DELETE", url);
      } catch (e) {
        // 404 = nothing in the DB; the cell only existed locally. Anything
        // else (4xx/5xx) is a real failure we surface to the user.
        const msg = e instanceof Error ? e.message : "";
        if (!/^404:/.test(msg)) {
          throw e;
        }
      }
      await queryClient.invalidateQueries({ queryKey: ["/api/timetable"] });
    } catch (e) {
      toast({
        title: "Could not remove",
        description: extractApiErrorMessage(e, "Server rejected the removal."),
        variant: "destructive",
      });
      return;
    }

    setTimetable((prev) => {
      const newTimetable = new Map(prev);
      const key = getSlotKey(
        selectedSlot.day,
        selectedSlot.schoolClass,
        selectedSlot.period
      );

      const previousSlot = newTimetable.get(key);

      const emptySlot: TimetableSlot = {
        ...selectedSlot,
        status: "empty",
        subject: null,
        teacherId: null,
        slotType: null,
        slashPairSubject: null,
        slashPairTeacherId: null,
      };

      newTimetable.set(key, emptySlot);

      if (previousSlot?.slotType === "double") {
        const nextKey = getSlotKey(
          selectedSlot.day,
          selectedSlot.schoolClass,
          selectedSlot.period + 1
        );
        const nextSlot = newTimetable.get(nextKey);
        if (nextSlot) {
          newTimetable.set(nextKey, {
            ...nextSlot,
            status: "empty",
            subject: null,
            teacherId: null,
            slotType: null,
            slashPairSubject: null,
            slashPairTeacherId: null,
          });
        }
      }

      if (previousSlot) {
        const action: TimetableAction = {
          id: crypto.randomUUID(),
          type: "remove",
          timestamp: Date.now(),
          slot: emptySlot,
          previousSlot,
        };

        setActions((prev) => {
          const newActions = prev.slice(0, actionIndex + 1);
          return [...newActions, action];
        });
        setActionIndex((prev) => prev + 1);
      }

      return newTimetable;
    });

    toast({
      title: "Period cleared",
      description: `Removed ${selectedSlot.subject} from ${selectedSlot.day} P${selectedSlot.period}`,
    });

    setDialogOpen(false);
    setSelectedSlot(null);
    setValidation(null);
  }, [selectedSlot, toast, actionIndex]);

  const handleUndo = useCallback(() => {
    if (actionIndex < 0) return;

    const action = actions[actionIndex];
    if (!action) return;

    setTimetable((prev) => {
      const newTimetable = new Map(prev);
      const key = getSlotKey(action.slot.day, action.slot.schoolClass, action.slot.period);

      if (action.previousSlot) {
        newTimetable.set(key, action.previousSlot);

        if (action.previousSlot.slotType === "double" || action.slot.slotType === "double") {
          const nextKey = getSlotKey(
            action.slot.day,
            action.slot.schoolClass,
            action.slot.period + 1
          );
          if (action.type === "place" && action.previousSlot.status === "empty") {
            const nextSlot = newTimetable.get(nextKey);
            if (nextSlot) {
              newTimetable.set(nextKey, {
                ...nextSlot,
                status: "empty",
                subject: null,
                teacherId: null,
                slotType: null,
                slashPairSubject: null,
                slashPairTeacherId: null,
                isLocked: false,
              });
            }
          }
        }
      } else {
        newTimetable.set(key, {
          ...action.slot,
          status: "empty",
          subject: null,
          teacherId: null,
          slotType: null,
          slashPairSubject: null,
          slashPairTeacherId: null,
          isLocked: false,
        });
      }

      return newTimetable;
    });

    setActionIndex((prev) => prev - 1);

    toast({
      title: "Undone",
      description: `Reverted ${action.type === "place" ? "placement" : "removal"} of ${action.slot.subject || "period"}`,
    });
  }, [actions, actionIndex, toast]);

  const handleRedo = useCallback(() => {
    if (actionIndex >= actions.length - 1) return;

    const action = actions[actionIndex + 1];
    if (!action) return;

    setTimetable((prev) => {
      const newTimetable = new Map(prev);
      const key = getSlotKey(action.slot.day, action.slot.schoolClass, action.slot.period);

      newTimetable.set(key, action.slot);

      if (action.slot.slotType === "double") {
        const nextKey = getSlotKey(
          action.slot.day,
          action.slot.schoolClass,
          action.slot.period + 1
        );
        const nextSlot = newTimetable.get(nextKey);
        if (nextSlot) {
          newTimetable.set(nextKey, {
            ...nextSlot,
            status: action.slot.status,
            subject: action.slot.subject,
            teacherId: action.slot.teacherId,
            slotType: "double",
            slashPairSubject: action.slot.slashPairSubject,
            slashPairTeacherId: action.slot.slashPairTeacherId,
          });
        }
      }

      return newTimetable;
    });

    setActionIndex((prev) => prev + 1);

    toast({
      title: "Redone",
      description: `Re-applied ${action.type === "place" ? "placement" : "removal"} of ${action.slot.subject || "period"}`,
    });
  }, [actions, actionIndex, toast]);

  const canUndo = actionIndex >= 0;
  const canRedo = actionIndex < actions.length - 1;

  const handleAutoGenerate = useCallback((options: { lockExisting: boolean; clearFirst: boolean }) => {
    autoGenerateMutation.mutate(options);
  }, [autoGenerateMutation]);

  const resetTimetableMutation = useMutation({
    mutationFn: async () => {
      await apiRequest("DELETE", "/api/timetable");
    },
    onSuccess: async () => {
      // Wipe local state and let the server query refetch (which will be
      // empty). Also clear the session-only undo/redo stack since every
      // referenced slot is gone.
      setTimetable(initializeTimetable());
      setActions([]);
      setActionIndex(-1);
      await queryClient.invalidateQueries({ queryKey: ["/api/timetable"] });
      setResetDialogOpen(false);
      toast({
        title: "Timetable reset",
        description: "Every period has been cleared. Start fresh whenever you're ready.",
      });
    },
    onError: (e: unknown) => {
      toast({
        title: "Reset failed",
        description: extractApiErrorMessage(e, "Could not reset the timetable."),
        variant: "destructive",
      });
    },
  });

  const saveTimetableMutation = useMutation({
    mutationFn: async (name: string) => {
      // Snapshot the live client grid (source of truth for unsaved edits)
      const slots = Array.from(timetable.values());
      const response = await apiRequest("POST", "/api/saved-timetables", { name, slots });
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/saved-timetables"] });
      toast({
        title: "Timetable saved",
        description: "View it on the Saved Timetables page.",
      });
      setSaveDialogOpen(false);
      setSaveName("");
    },
    onError: (error: Error) => {
      toast({
        title: "Save failed",
        description: error.message || "Could not save timetable.",
        variant: "destructive",
      });
    },
  });

  const occupiedCount = Array.from(timetable.values()).filter(
    (s) => s.status === "occupied"
  ).length;

  const handleOpenSaveDialog = () => {
    if (occupiedCount === 0) {
      toast({
        title: "Nothing to save",
        description: "Place at least one period before saving.",
        variant: "destructive",
      });
      return;
    }
    setSaveName(`Timetable ${new Date().toLocaleDateString()}`);
    setSaveDialogOpen(true);
  };

  return (
    <div className="flex flex-col min-h-full">
      <div className="p-4 border-b space-y-3">
        <StatsHeader 
          timetable={timetable} 
          teachers={teachers}
          onAutoGenerate={() => setAutoGenDialogOpen(true)}
          isGenerating={autoGenerateMutation.isPending}
          selectedDay={selectedDay}
          gridRef={gridRef}
          maxFreePeriodsPerWeek={userSettings?.maxFreePeriodsPerWeek}
          maxFreePeriodsPerDay={userSettings?.maxFreePeriodsPerDay}
          freePeriodsPerClass={userSettings?.freePeriodsPerClass}
        />
        <div className="flex justify-end gap-2">
          <Button
            variant="outline"
            onClick={() => setResetDialogOpen(true)}
            disabled={resetTimetableMutation.isPending}
            className="text-destructive hover:text-destructive"
            data-testid="button-reset-timetable"
          >
            <Trash2 className="h-4 w-4 mr-2" />
            Reset Timetable
          </Button>
          <Button
            variant="outline"
            onClick={handleOpenSaveDialog}
            data-testid="button-save-timetable"
          >
            <Save className="h-4 w-4 mr-2" />
            Save Timetable
          </Button>
        </div>
      </div>

      <div className="flex flex-1 min-h-0">
        <div className="flex-1 overflow-auto p-4">
          <div ref={gridRef}>
            <TimetableGrid
              timetable={timetable}
              teachers={teachers}
              selectedDay={selectedDay}
              onDayChange={setSelectedDay}
              onCellClick={handleCellClick}
            />
          </div>
        </div>

        <div className="w-80 border-l overflow-y-auto p-4 space-y-4 hidden lg:block">
          <TeacherSidebar teachers={teachers} timetable={timetable} />
        </div>

        <div className="w-72 border-l overflow-y-auto p-4 space-y-4 hidden xl:block">
          <SubjectTracker timetable={timetable} quotas={quotas} />
          <ActionHistory
            actions={actions}
            currentIndex={actionIndex}
            onUndo={handleUndo}
            onRedo={handleRedo}
            canUndo={canUndo}
            canRedo={canRedo}
          />
        </div>
      </div>

      <PlacementDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        slot={selectedSlot}
        teachers={teachers}
        customSubjects={customSubjects}
        onPlace={handlePlace}
        onRemove={handleRemove}
        validation={validation}
        onValidate={handleValidate}
      />

      <AutoGenerateDialog
        open={autoGenDialogOpen}
        onOpenChange={setAutoGenDialogOpen}
        onGenerate={handleAutoGenerate}
        isGenerating={autoGenerateMutation.isPending}
        result={autoGenerateMutation.data}
        onSave={() => {
          setAutoGenDialogOpen(false);
          handleOpenSaveDialog();
        }}
      />

      <AlertDialog
        open={resetDialogOpen}
        onOpenChange={(o) => !resetTimetableMutation.isPending && setResetDialogOpen(o)}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Reset the entire timetable?</AlertDialogTitle>
            <AlertDialogDescription>
              This will erase every period for every class — including fixed
              periods and non-teaching activities. This cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel
              disabled={resetTimetableMutation.isPending}
              data-testid="button-reset-cancel"
            >
              Cancel
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={(e) => {
                e.preventDefault();
                resetTimetableMutation.mutate();
              }}
              disabled={resetTimetableMutation.isPending}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              data-testid="button-reset-confirm"
            >
              {resetTimetableMutation.isPending ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <Trash2 className="h-4 w-4 mr-2" />
              )}
              Yes, reset everything
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <Dialog open={saveDialogOpen} onOpenChange={setSaveDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Save Timetable</DialogTitle>
            <DialogDescription>
              Snapshot your current grid. You can reload it later from the Saved Timetables page.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-2">
            <Label htmlFor="save-name">Name</Label>
            <Input
              id="save-name"
              value={saveName}
              onChange={(e) => setSaveName(e.target.value)}
              placeholder="e.g., Term 1 Final"
              maxLength={100}
              data-testid="input-save-name"
            />
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setSaveDialogOpen(false)}
              disabled={saveTimetableMutation.isPending}
            >
              Cancel
            </Button>
            <Button
              onClick={() => saveTimetableMutation.mutate(saveName.trim())}
              disabled={!saveName.trim() || saveTimetableMutation.isPending}
              data-testid="button-confirm-save"
            >
              {saveTimetableMutation.isPending ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <Save className="h-4 w-4 mr-2" />
              )}
              Save
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
