import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Wand2, Loader2, AlertTriangle, CheckCircle2, Info, Save } from "lucide-react";
import type { AutoGenerateResult } from "@shared/schema";

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onGenerate: (options: { lockExisting: boolean; clearFirst: boolean }) => void;
  isGenerating: boolean;
  result?: AutoGenerateResult;
  onSave?: () => void;
}

export function AutoGenerateDialog({
  open,
  onOpenChange,
  onGenerate,
  isGenerating,
  result,
  onSave,
}: AutoGenerateDialogProps) {
  const [lockExisting, setLockExisting] = useState(false);
  const [clearFirst, setClearFirst] = useState(true);

  const handleGenerate = () => {
    onGenerate({ lockExisting, clearFirst });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Wand2 className="h-5 w-5 text-primary" />
            Auto-Generate Timetable
          </DialogTitle>
          <DialogDescription>
            Automatically fill the timetable based on your configured subject quotas and validation rules.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <Alert>
            <Info className="h-4 w-4" />
            <AlertTitle>How it works</AlertTitle>
            <AlertDescription className="text-sm">
              The system will schedule subjects according to your quota settings, respecting all validation rules including teacher availability, clash prevention, and fatigue limits.
            </AlertDescription>
          </Alert>

          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <Checkbox
                id="lockExisting"
                checked={lockExisting}
                onCheckedChange={(checked) => setLockExisting(checked === true)}
                data-testid="checkbox-lock-existing"
              />
              <div className="grid gap-1.5 leading-none">
                <Label htmlFor="lockExisting" className="font-medium">
                  Keep existing placements
                </Label>
                <p className="text-sm text-muted-foreground">
                  Preserve any subjects you've already scheduled and fill around them.
                </p>
              </div>
            </div>

            <div className="flex items-start space-x-3">
              <Checkbox
                id="clearFirst"
                checked={clearFirst}
                onCheckedChange={(checked) => setClearFirst(checked === true)}
                disabled={lockExisting}
                data-testid="checkbox-clear-first"
              />
              <div className="grid gap-1.5 leading-none">
                <Label htmlFor="clearFirst" className={`font-medium ${lockExisting ? "text-muted-foreground" : ""}`}>
                  Clear timetable first
                </Label>
                <p className="text-sm text-muted-foreground">
                  Start with a clean slate before generating. Ignored if keeping existing placements.
                </p>
              </div>
            </div>
          </div>

          {result && (
            <ScrollArea className="max-h-40">
              <div className="space-y-2">
                {result.success ? (
                  <Alert className="border-green-500/50 bg-green-500/10">
                    <CheckCircle2 className="h-4 w-4 text-green-500" />
                    <AlertTitle className="text-green-600">Generation Complete</AlertTitle>
                    <AlertDescription className="text-sm">
                      Successfully placed {result.slotsPlaced} periods.
                    </AlertDescription>
                  </Alert>
                ) : (
                  <Alert variant="destructive">
                    <AlertTriangle className="h-4 w-4" />
                    <AlertTitle>Generation had issues</AlertTitle>
                    <AlertDescription className="text-sm">
                      {result.errors.join(", ")}
                    </AlertDescription>
                  </Alert>
                )}

                {result.warnings.length > 0 && (
                  <Alert className="border-amber-500/50 bg-amber-500/10">
                    <AlertTriangle className="h-4 w-4 text-amber-500" />
                    <AlertTitle className="text-amber-600">Warnings</AlertTitle>
                    <AlertDescription>
                      <ul className="list-disc list-inside text-sm space-y-1">
                        {result.warnings.slice(0, 10).map((warning, i) => (
                          <li key={i}>{warning}</li>
                        ))}
                        {result.warnings.length > 10 && (
                          <li className="text-muted-foreground">
                            ...and {result.warnings.length - 10} more warnings
                          </li>
                        )}
                      </ul>
                    </AlertDescription>
                  </Alert>
                )}
              </div>
            </ScrollArea>
          )}

          {!result && (
            <Alert variant="destructive" className="border-destructive/50 bg-destructive/10">
              <AlertTriangle className="h-4 w-4" />
              <AlertTitle>Warning</AlertTitle>
              <AlertDescription className="text-sm">
                {lockExisting 
                  ? "Existing placements will be preserved. Empty slots will be filled."
                  : clearFirst 
                    ? "This will clear your current timetable and generate a new one." 
                    : "This will attempt to fill empty slots without clearing existing content."
                }
              </AlertDescription>
            </Alert>
          )}
        </div>

        <DialogFooter>
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={isGenerating}
            data-testid="button-cancel-generate"
          >
            {result ? "Close" : "Cancel"}
          </Button>
          {result?.success && onSave && (
            <Button
              variant="outline"
              onClick={onSave}
              disabled={isGenerating}
              data-testid="button-save-after-generate"
            >
              <Save className="h-4 w-4 mr-2" />
              Save Timetable
            </Button>
          )}
          <Button
            onClick={handleGenerate}
            disabled={isGenerating}
            data-testid="button-confirm-generate"
          >
            {isGenerating ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Wand2 className="h-4 w-4 mr-2" />
                {result ? "Generate Again" : "Generate Timetable"}
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
